#travis configuration for coverage testing
language: c++

#sudo: false # only for faster builds

before_script: 
- cd ${TRAVIS_BUILD_DIR}

# Compiler selection
compiler:
  - clang
  - gcc

# Build steps
script: 
  - cmake .. && make .

after_success:
- cd ${TRAVIS_BUILD_DIR}